config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'lunch_posts#index'
  get 'posts' => 'application#back_redirect'  
  get 'users' => 'application#back_redirect'  
  resources :lunch_posts , path: "posts", as: "posts", except: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/lunch_post.rb
class LunchPost < ApplicationRecord
  mount_uploader :image_path, ImageUploader
  belongs_to :user
  belongs_to :prefecture
  belongs_to :station

  validates :title, presence: true, length: { maximum: 100 }
  validates :shop_name, length: { maximum: 100 }
  validates :price, length: { maximum: 5 }, presence: true
  validates :image_path, presence: true

  scope :is_active, -> { where(is_active: true) }
end

app/models/prefecture.rb
class Prefecture < ApplicationRecord
  has_many :stations
  has_many :lunch_posts
  has_many :users
end

app/models/station.rb
class Station < ApplicationRecord
  belongs_to :prefecture
  has_many :users
  has_many :lunch_posts
end

app/models/user.rb
class User < ApplicationRecord
  mount_uploader :image_path, ImageUploader
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def back_redirect
    redirect_back(fallback_location: root_path)
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |user_params|
      user_params.permit(:email, :password, :name, :image_path)
    end
  end

end

app/controllers/lunch_posts_controller.rb
class LunchPostsController < ApplicationController

  before_action :authenticate_user!, only: [:new]
  before_action :set_lunch_post, only: [:edit, :update, :destroy]
  before_action :posted_user?, only: [:edit, :update, :destroy]

  def index 
    @lunch_posts = LunchPost.is_active
  end

  def show
    redirect_back(fallback_location: root_path)
  end

  def new 
    @lunch_post = LunchPost.new
  end

  def create
    @lunch_post = LunchPost.new(post_params)
    if @lunch_post.save
      redirect_to root_path, notice: "投稿しました。"
    else
      flash.now[:alert] = "未入力項目があります。"
      render 'new'
    end
  end

  def edit
  end

  def update
    if @lunch_post.update(post_params)
      redirect_to root_path, notice: "更新しました。"
    else
      flash[:alert] = "未入力項目があります。"
      render 'edit'
    end
  end

  def destroy
    if @lunch_post.delete
      redirect_to root_path, notice: "削除しました"
    else
      flash.now[:alert] = "削除できませんでした"
      render 'index'
    end
  end

  private 
    def post_params
      params.require(:lunch_post).permit!
    end

    def set_lunch_post
      @lunch_post = LunchPost.find(params[:id])
    end

    def posted_user?
      unless current_user == @lunch_post.user
        redirect_to root_path
      end
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Lunch
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    = render "shared/flash"
    = yield

app/views/lunch_posts/_form.html.slim
= form_with model: post, url: url, local: true do |f|
  = f.hidden_field :user_id, value: current_user.id
  = f.hidden_field :prefecture_id, value: 1
  = f.hidden_field :station_id, value: 1
  ul
    li
      = f.label :title
      = f.text_field :title
    li
      = f.label :price
      = f.text_field :price
    li
      = f.label :shop_name
      = f.text_field :shop_name
    li 
      = f.file_field :image_path
    li
      = f.submit

app/views/lunch_posts/edit.html.slim
= render "form", post: @lunch_post, url: post_path(@lunch_post.id)

app/views/lunch_posts/index.html.slim
= link_to "新規投稿", new_post_path
- @lunch_posts.each do |post|
  div
    = post.title 
    = post.shop_name
    = post.price
    = image_tag(post.image_path)
    br
    - if current_user.present? && current_user == post.user
      = link_to "削除", post_path(post.id.to_i), method: :delete
      br
      = link_to "編集する", edit_post_path(post.id)

app/views/lunch_posts/new.html.slim
h1 新規登録 
= render "form", post: @lunch_post, url: posts_path

app/views/shared/_flash.html.slim
- if flash.present?
  - flash.each do |key, value| 
    = value

app/views/users/shared/_links.html.slim
- if controller_name != 'sessions'
  = link_to "Log in", new_session_path(resource_name)
  br
- if devise_mapping.registerable? && controller_name != 'registrations'
  = link_to "Sign up", new_registration_path(resource_name)
  br
- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations'
  = link_to "Forgot your password?", new_password_path(resource_name)
  br
- if devise_mapping.confirmable? && controller_name != 'confirmations'
  = link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name)
  br
- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks'
  = link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name)
  br
- if devise_mapping.omniauthable?
  - resource_class.omniauth_providers.each do |provider|
    = link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider)
    br